name: app1
replicas: 1
image: gcr.io/$PROJECT_ID/app1
port: 5000
ingress:
  enabled: true
  name: app1-ingress
  className: gce
  host: app1.thinkingtab.com
  serviceName: app1
  path: /*
  pathType: ImplementationSpecific
  servicePort: 80
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "app1.thinkingtab.com"
    kubernetes.io/ingress.class: "gce"
secret:
  enabled: true
  secretName: external-dns-sa
  target: secret-example

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
