apps:
  - name: app1
    replicas: 1
    image: gcr.io/your-project-id/app1
    port: 5000
    ingress:
      enabled: true
      name: app1-ingress
      className: nginx
      host: app1.$INGRESS_IP.nip.io
      serviceName: app1
      path: /*
      pathType: ImplementationSpecific
      servicePort: 80
      # annotations:
        # nginx.ingress.kubernetes.io/rewrite-target: /

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
