{{- if .Values.secret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-example
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: {{ .Values.secret.target }}
  data:
    - secretKey: sample-key
      remoteRef:
        key: {{ .Values.secret.secretName }}
{{- end }}